server:
  port: 8083

spring:
  liquibase:
    enabled: false

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8762/realms/fitness-app


